title: 2011Scape
description: An open-source 2011 RuneScape emulator
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  url: https://github.com/2011Scape

discord:
  url: https://discord.gg/jDbBAKjhxh

forums:
  url: https://forum.2011scape.com

download:
  url: https://2011scape.com/downloads/2011Scape.jar